### ISSUE TITLE
How this works????

### ISSUE THREAD

**Issue by SoulsCombat** [AdamantPenguin/BookletX#3]
How does this hack work and where do you paste this code????

**Comment by AdamantPenguin** [comment]
> How does this hack work

Well actually it doesn't anymore (blooket changed the API and this app is mostly unmaintained) — what it's supposed to do is send HTTP requests to the Blooket API in order to join a game, then use the Firebase library to actually participate in the game

> where do you paste this code????

You don't. This is an Android app. If you want to use it (which you don't, because it doesn't work anymore), please read 'How do I get it' in the [readme](https://github.com/AdamantPenguin/BookletX/blob/main/README.md)

**Comment by SoulsCombat** [comment]
ok ty
